---
config:
    class:
        hideEmptyMembersBox: true
    theme: default
    look: classic
    layout: dagre
---
classDiagram
    direction LR

    class Session {
        +ObjectId id
        +string token
        +User user
        +string userAgent
        +Date createdAt
        +Date expiresAt

        +isExpired() Boolean*
    }
    Session "0..*" <-- "1" User : creates

    class VerificationCode {
        +ObjectId id
        +User user
        +string code
        +Date createdAt
        +Date expiresAt

        +sendEmail() Promise~void~$
        +validateCode()$ boolean
    }
    VerificationCode "1..*" --> "1" User : contains

    class Notification {
        +ObjectId id
        +string title
        +string content
        +User user
        +Exam? exam
        +User? owner
        +Date createdAt
        +Date? readAt

        +markAsRead() Promise~void~
    }

    class User {
        +ObjectId id
        +string name
        +string email
        +string normalizedEmail
        +string username
        +string password
        +string accountType
        +Date createdAt
        +Date? updatedAt
        +object settings

        +generateToken() Promise~String~$
        +hashPassword(password: string) String$

        +validatePassword(password: string) Boolean
        +authenticate() Promise~Session~*
        +logout() Promise~void~*

        +createExam(exam: Exam) ~Promise~*
        +startExam(exam: Exam) Promise~StartedExam~*
        +submitExam(exam: Exam) Promise~Submit~*

        +sendAnswerFeedback(answer: Answer, isCorrect: Boolean, feedback?: String) Promise~void~*
    }
    User "1..*" --> "0..*" Notification : receives
    User "1" --> "1..*" Notification : sends
    User "1" --> "0..*" StartedExam : contains
    User "1" --> "0..*" Exam : creates
    User "0..*" --> "0..*" Exam : participates
    User "1" --> "0..*" Submit : performs

    class StartedExam {
        +ObjectId id
        +Exam exam
        +User user
        +Date createdAt

        +isExpired() Promise~boolean~
        +getSubmitData() Promise~object~*
    }
    StartedExam "1" --> "1" Exam : refers

    class Exam {
        +ObjectId id
        +User owner
        +string title
        +string description
        +string? subject
        +number duration
        +Question[] questions
        +User[] candidates
        +User[] disallowedCandidates
        +Date createdAt
        +Date? updatedAt
        +Date? expiresAt
        +Date? startsAt

        +editExam(exam: Exam) Promise~void~*
        +getMaxGrade() Number*
        +isExpired() boolean
    }
    Exam "1" --> "1" ExamInvite : contains
    Exam "1" --> "1..*" Question : contains
    Exam "1" --> "0..*" Submit : allows

    class ExamInvite {
        +ObjectId id
        +string token
        +Exam exam
        +Date createdAt
    }

    class Question {
        +ObjectId id
        +string type
        +string text
        +boolean isRequired
		+string? feedback
        +QuestionOption[]? options
        +string? correctAnswer
    }
    Question "1" --> "0..*" QuestionOption : contains
    Question "1" --> "1" Answer : allows

    class QuestionOption {
        +ObjectId id
        +string text
    }

    class Answer {
        +ObjectId id
        +string type
        +Submit submit
        +Question question
        +QuestionOption? option
        +string? content
        +boolean? isCorrect
		+string? feedback
        +Date createdAt
        +Date? updatedAt
    }
    Answer "1" --> "0..1" QuestionOption : contains
    Answer "0..*" <-- "1" Submit : contains

    class Submit {
        +ObjectId id
        +User user
        +Exam exam
        +Date createdAt
        +Date publishedAt

        +getAnswers() Promise~Answer[]~
        +getGrade() Promise~Number~*
        +isPendingCorrection() Promise~boolean~
        +sendNotification(exam: Exam, user: User) Promise~void~$
    }
