---
config:
    class:
        hideEmptyMembersBox: true
    theme: default
    look: classic
    layout: dagre
---
erDiagram
    Session {
        ObjectId id PK
        String(96) token
        ObjectId user FK
        String(255) userAgent
        Date createdAt
        Date expiresAt
    }

    VerificationCode {
        ObjectId id PK
        ObjectId user FK
        String(10) code
        Date createdAt
        Date expiresAt
    }

    Notification {
        ObjectId id
        string title
        string content
        User user
        Exam exam
        User owner
        Date createdAt
        Date readAt
    }

    User {
        ObjectId id PK
        String(255) name
        String(255) email
        String(255) normalizedEmail
        String(30) username
        String(255) password
        String(255) accountType
        Date createdAt
        Date updatedAt
        Object settings
    }
    User 1--0+ Session : creates
    User 1--1+ VerificationCode : requests
    User 1+--0+ Notification : receives
    User 1--1+ Notification : sends
    User 1--0+ Exam : creates
    User 0+--0+ Exam : participates
    User 1--0+ StartedExam : starts
    User 1--0+ Submit : performs

    StartedExam {
        ObjectId id PK
        ObjectId exam FK
        ObjectId user FK
        Date createdAt
    }
    StartedExam 1--0+ Exam : refers

    Exam {
        ObjectId id PK
        ObjectId owner FK
        String(255) title
        String(355) description
        String(255) subject
        Number duration
        ObjectId[] candidates FK
        ObjectId[] disallowedCandidates FK
        Date createdAt
        Date updatedAt
        Date expiresAt
        Date startsAt
    }
    Exam 1--1+ ExamInvite : contains
    Exam 1--1+ Question : contains
    Exam 1--0+ Submit : allows

    ExamInvite {
        ObjectId id PK
        String(96) token
        ObjectId exam FK
        Date createdAt
    }

    Question {
        ObjectId id PK
        String(255) type
        String(2000) text
        Boolean isRequired
        ObjectId correctAnswer FK
        String(2000) feedback
    }
    Question 1--0+ Answer : allows
    Question 1--0+ QuestionOption : contains

    QuestionOption {
        ObjectId id PK
        String(255) text
    }

    Answer {
        ObjectId id PK
        String(255) type
        ObjectId submit FK
        ObjectId question FK
        ObjectId option FK
        String(2000) content
        Boolean isCorrect
        String(2000) feedback
        Date createdAt
        Date updatedAt
    }
    Answer 1--zero or one QuestionOption : contains

    Submit {
        ObjectId id PK
        ObjectId user FK
        ObjectId exam FK
        Date createdAt
        Date publishedAt
    }
